### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by moxie-coder** [fnfporterhi/SHAGGY#4]
I can't speak now in here https://github.com/fnfporterhi/SHAGGY/issues/1 @fnfporterhi

**Comment by fnfporterhi** [comment]
umm youre a collaborator though. hold on.

**Comment by fnfporterhi** [comment]
ohhh lmao i thought contributor was a collaborator. added you.

**Comment by fnfporterhi** [comment]
fixed!

**Comment by moxie-coder** [comment]
👍🏻

**Comment by Lucas-Pat** [comment]
Thanks @fnfporterhi
[Screen recording 2024-01-29 10.01.18 PM.webm](https://github.com/fnfporterhi/SHAGGY/assets/158116771/df80b9fd-58ad-4a2f-b5be-0b3adec5e13e)
[Screen recording 2024-01-29 10.02.31 PM.webm](https://github.com/fnfporterhi/SHAGGY/assets/158116771/eba20cc6-a449-4251-9108-392123252a99)
![Screenshot (196)](https://github.com/fnfporterhi/SHAGGY/assets/158116771/62ef61b6-750a-4d19-a92e-259a141dccc6)
![Screenshot (193)](https://github.com/fnfporterhi/SHAGGY/assets/158116771/a62d9a2f-2c9a-407f-b412-4a205c1164f8)
Sherri, I just uploaded in Windows 10.
[Screen recording 2024-01-29 10.03.42 PM.webm](https://github.com/fnfporterhi/SHAGGY/assets/158116771/91240e4a-a445-4425-8e02-89830158fa6c)
hi ab
