### ISSUE TITLE
It just won't load

### ISSUE THREAD

**Issue by Meme-man-LOL** [fnfporterhi/SHAGGY#6]
So like the game won't load and stuff

**Comment by moxie-coder** [comment]
we are working on that, or more specifically I am, I’ll do more work when I get home

**Comment by moxie-coder** [comment]
and make your issue more detailed next time

**Comment by Lucas-Pat** [comment]
no @fnfporterhi here, but ab @moxie-coder or @meme-man-LOL

**Comment by Lucas-Pat** [comment]
[Screen recording 2024-01-29 9.56.40 PM.webm](https://github.com/fnfporterhi/SHAGGY/assets/158116771/058b4bd7-2590-4164-81d2-3ef42edc855c)

**Comment by Lucas-Pat** [comment]
ab i just send to screen recordings
![Screenshot 2024-01-29 9 57 31 PM](https://github.com/fnfporterhi/SHAGGY/assets/158116771/eda87e1b-67bd-4479-93fa-fefb9ab84265)
![Screenshot 2024-01-29 9 58 46 PM](https://github.com/fnfporterhi/SHAGGY/assets/158116771/6272cf1d-3bb9-4007-87e0-a25bd2eac698)

**Comment by Lucas-Pat** [comment]
[Screen recording 2024-01-29 9.59.30 PM.webm](https://github.com/fnfporterhi/SHAGGY/assets/158116771/f5f6cab9-6ae5-461e-a3b4-7e76ad1da34b)

**Comment by fnfporterhi** [comment]
quit. im not whoever tf that is
