### ISSUE TITLE
gmail hi ab

### ISSUE THREAD

**Issue by Lucas-Pat** [fnfporterhi/SHAGGY#7]
hi ab gmail. @fnfporterhi Don't swear it, ab just send to gmail.
![Screenshot 2024-01-29 9 51 19 PM](https://github.com/fnfporterhi/SHAGGY/assets/158116771/37420a82-5ab9-4b6b-83fb-88d479bcd0f1)

**Comment by Lucas-Pat** [comment]
alright, @fnfporterhi upload the screen recording, but don't swear words either
[Screen recording 2024-01-29 9.52.55 PM.webm](https://github.com/fnfporterhi/SHAGGY/assets/158116771/de752854-6d17-4c50-bb20-172a6f64e58e)
@levixddlmao i just sent to gmail.

**Comment by fnfporterhi** [comment]
huh?

**Comment by fnfporterhi** [comment]
bro that aint me :skull:
