### ISSUE TITLE
screenshots like windows 10

### ISSUE THREAD

**Issue by Lucas-Pat** [fnfporterhi/SHAGGY#8]
hi ab
![Screenshot (196)](https://github.com/fnfporterhi/SHAGGY/assets/158116771/ee874635-322e-45ee-af7e-31ee8c933afe)
![Screenshot (193)](https://github.com/fnfporterhi/SHAGGY/assets/158116771/f968974a-ca66-47ab-beaa-79d1ea679699)
windows 10

**Comment by moxie-coder** [comment]
shut the fuck up, and get out this repo

**Comment by fnfporterhi** [comment]
please leave. i'm abt to go insane over this

i'm not who u think i am

follow moxies instructions and get the fuck outa here.

**Comment by fnfporterhi** [comment]
get your canadian bitch ass outa here.
